live_config_reload: true

decorations: "None"

chosen_font: &font "CaskaydiaCoveNerdFont"
#chosen_font: &font "Cascadia Code"

# Font configuration
font: #   # Normal (roman) font face
  normal:
     #Font family

     # Default:
       # - (macOS) Menlo
       # - (Linux/BSD) monospace
       # - (Windows) Consolas
    family: *font

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: *font

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: *font

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: *font

    # The `style` can be specified to pick a specific face.
    style: BoldItalic

  # Point size
  #size: 11.0

colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    colors.footer_bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'

# # Colors (Blood Moon)
# colors:
#   # Default colors
#   primary:
#     background: '#181D1D'
#     foreground: '#C6C6C4'
#
#   # Normal colors
#   normal:
#     black:   '#10100E'
#     red:     '#C40233'
#     green:   '#009F6B'
#     yellow:  '#FFD700'
#     blue:    '#0087BD'
#     magenta: '#9A4EAE'
#     cyan:    '#20B2AA'
#     white:   '#C6C6C4'
#
#   # Bright colors
#   bright:
#     black:   '#696969'
#     red:     '#FF2400'
#     green:   '#03C03C'
#     yellow:  '#FDFF00'
#     blue:    '#007FFF'
#     magenta: '#FF1493'
#     cyan:    '#00CCCC'
#     white:   '#FFFAFA'

# # Base16 Ocean - alacritty color config
# # Chris Kempson (http://chriskempson.com)
# colors:
#   # Default colors
#   primary:
#     background: '0x2b303b'
#     foreground: '0xc0c5ce'
# 
#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x2b303b'
#     cursor: '0xc0c5ce'
# 
#   # Normal colors
#   normal:
#     black:   '0x2b303b'
#     red:     '0xbf616a'
#     green:   '0xa3be8c'
#     yellow:  '0xebcb8b'
#     blue:    '0x8fa1b3'
#     magenta: '0xb48ead'
#     cyan:    '0x96b5b4'
#     white:   '0xc0c5ce'
# 
#   # Bright colors
#   bright:
#     black:   '0x65737e'
#     red:     '0xd08770'
#     green:   '0x343d46'
#     yellow:  '0x4f5b66'
#     blue:    '0xa7adba'
#     magenta: '0xdfe1e8'
#     cyan:    '0xab7967'
#     white:   '0xeff1f5'
# 
# draw_bold_text_with_bright_colors: false
